# Generated by Django 3.1.3 on 2020-11-06 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovieDetails_app', '0002_auto_20201106_1115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='Title',
            new_name='title',
        ),
    ]
